version: "3.1"


services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres-np
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 1@1.ru
      PGADMIN_DEFAULT_PASSWORD: pass
    links:
      - "db:pgsql-server"